[project]
name = "codesandbox"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asgiref>=3.8",
    "app-router",
    "nexorm",
    "psycopg[binary]>=3.2",
    "uvicorn[standard]>=0.30",
]

[tool.uv.workspace]
members = [
    "packages/app_router",
    "packages/nexorm",
]

[tool.uv.sources]
app-router = { workspace = true, editable = true }
nexorm = { workspace = true, editable = true }
