from nexorm.migrations.operations import *

operations = [
    CreateTable(name='sandbox_template_plans', columns=[
        {'name': 'id', 'type': 'StringField', 'nullable': False, 'unique': False, 'default': None,
         'primary_key': True, 'index': False, 'auto_increment': False, 'max_length': 36,
         'max_digits': None, 'decimal_places': None, 'foreign_key': None},
        {'name': 'template_id', 'type': 'ForeignKey', 'nullable': False, 'unique': False, 'default': None,
         'primary_key': False, 'index': True, 'auto_increment': False, 'max_length': None,
         'max_digits': None, 'decimal_places': None,
         'foreign_key': {'to': 'SandboxTemplate', 'on_delete': 'CASCADE', 'related_name': None,
                         'target_field': {'type': 'StringField', 'primary_key': True, 'nullable': False,
                                          'unique': False, 'default': None, 'index': False,
                                          'auto_increment': False, 'max_length': 36}}},
        {'name': 'plan_id', 'type': 'StringField', 'nullable': False, 'unique': False, 'default': None,
         'primary_key': False, 'index': False, 'auto_increment': False, 'max_length': 40,
         'max_digits': None, 'decimal_places': None, 'foreign_key': None},
        {'name': 'ind_vcpu', 'type': 'IntegerField', 'nullable': True, 'unique': False, 'default': None,
         'primary_key': False, 'index': False, 'auto_increment': False, 'max_length': None,
         'max_digits': None, 'decimal_places': None, 'foreign_key': None},
        {'name': 'ind_ram_gb', 'type': 'IntegerField', 'nullable': True, 'unique': False, 'default': None,
         'primary_key': False, 'index': False, 'auto_increment': False, 'max_length': None,
         'max_digits': None, 'decimal_places': None, 'foreign_key': None},
        {'name': 'ind_disk_gb', 'type': 'IntegerField', 'nullable': True, 'unique': False, 'default': None,
         'primary_key': False, 'index': False, 'auto_increment': False, 'max_length': None,
         'max_digits': None, 'decimal_places': None, 'foreign_key': None},
        {'name': 'ind_cost_hr', 'type': 'DecimalField', 'nullable': True, 'unique': False, 'default': None,
         'primary_key': False, 'index': False, 'auto_increment': False, 'max_length': None,
         'max_digits': 10, 'decimal_places': 4, 'foreign_key': None},
        {'name': 'org_vcpu', 'type': 'IntegerField', 'nullable': True, 'unique': False, 'default': None,
         'primary_key': False, 'index': False, 'auto_increment': False, 'max_length': None,
         'max_digits': None, 'decimal_places': None, 'foreign_key': None},
        {'name': 'org_ram_gb', 'type': 'IntegerField', 'nullable': True, 'unique': False, 'default': None,
         'primary_key': False, 'index': False, 'auto_increment': False, 'max_length': None,
         'max_digits': None, 'decimal_places': None, 'foreign_key': None},
        {'name': 'org_disk_gb', 'type': 'IntegerField', 'nullable': True, 'unique': False, 'default': None,
         'primary_key': False, 'index': False, 'auto_increment': False, 'max_length': None,
         'max_digits': None, 'decimal_places': None, 'foreign_key': None},
        {'name': 'org_cost_hr', 'type': 'DecimalField', 'nullable': True, 'unique': False, 'default': None,
         'primary_key': False, 'index': False, 'auto_increment': False, 'max_length': None,
         'max_digits': 10, 'decimal_places': 4, 'foreign_key': None},
        {'name': 'is_enabled', 'type': 'BooleanField', 'nullable': False, 'unique': False, 'default': True,
         'primary_key': False, 'index': False, 'auto_increment': False, 'max_length': None,
         'max_digits': None, 'decimal_places': None, 'foreign_key': None},
        {'name': 'sort_order', 'type': 'IntegerField', 'nullable': False, 'unique': False, 'default': 0,
         'primary_key': False, 'index': False, 'auto_increment': False, 'max_length': None,
         'max_digits': None, 'decimal_places': None, 'foreign_key': None},
    ]),
]
